### ISSUE TITLE
Consolodate the phi field names in neo4j

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-ui#115]
Currently in neo4j, for the gene sequence attribute, we have phi , hasPHI , and hasphi mixed use in the metadata nodes. We'll need to normaliz the three into one consistent field for the file access check in gateway as well as ingest UI. May make a cypher query to change them if it's easier to do it right in the neo4j other than handling all three cases in the gateway file auth code.

**Comment by cborromeo** [comment]
I need to run some Cypher to fix this data on the back end: 

first, change the attribute to has_phi:
MATCH (e) WHERE e.phi IS NOT NULL SET e.has_phi = e.phi RETURN e.hasPHI, e.hasphi, e.phi, e.has_phi

second, remove extra attributes:
MATCH (e) REMOVE e.hasPHI, e.hasphi, e.phi RETURN e.hasPHI, e.hasphi, e.phi, e.has_phi

**Comment by cborromeo** [comment]
I am consolidating this attribute to 'phi' for now.  Eventually, I want to rename this 'has_phi'.  However, this affects the ingest-ui, gateway, and entity-api.  These are current deployed in different states using different branches (ex: master, 1.7, codex, etc.) across dev and test.  Gateway is using this attribute as part of the file pass-thru.  This is not the right time to make this change since it would represent several changes to several branches and code deployments.

**Comment by shirey** [comment]
Closing this now.  Suggesting in issue https://github.com/hubmapconsortium/search-api/issues/13 that we rename this remaining phi field.
