### ISSUE TITLE
Discuss badge colors and consistency across UIs

### ISSUE THREAD

**Issue by maxsibilla** [hubmapconsortium/ingest-ui#1224]
I have noticed that the colors that correspond with the various statuses across the Data Ingest Board, Ingest UI, and Portal UI are not consistent. For instance the color for QA is two different colors of blue between the Ingest and Portal UI and is yellow on the Data Ingest Board.
https://ingest.dev.hubmapconsortium.org/dataset/7479e6dbfa3b3a8e1e2d4f78cbe0f9e4
https://portal.dev.hubmapconsortium.org/browse/dataset/1f834ca5b75290df7773c51c8f4c7636

We should discuss and finalize a set of colors for all statuses and then implement them across the various HuBMAP and SenNet UI's.

**Comment by yuanzhou** [comment]
The badge colors update addressed via PR https://github.com/hubmapconsortium/data-ingest-board/pull/76

Additional fixes to the expired token made in the same branch but still present an issue:

https://github.com/hubmapconsortium/ingest-ui/assets/195873/5e9d20d0-3980-4bab-b133-cfab9e68f99b

We'll either fully resolve the login/logout issue or back out the changes and release the color update first.

**Comment by libpitt** [comment]
@yuanzhou The issue in the screen shot, has to do with ubkg, which presented itself recently. Resolved by putting a null check on that object..

The login/logout, that's because there was a request to apply `read_privs` on login response. When that change was made, it inadvertently made [this request](https://github.com/hubmapconsortium/data-ingest-board/blob/471e3c01881af09aebd2b9573004c422c3e9d8c4/src/service/ingest_api.js) seem obsolete.

It appears [this request](https://github.com/hubmapconsortium/data-ingest-board/blob/471e3c01881af09aebd2b9573004c422c3e9d8c4/src/service/ingest_api.js) along with [this method](https://github.com/hubmapconsortium/data-ingest-board/commit/471e3c01881af09aebd2b9573004c422c3e9d8c4#diff-3bb506a471395fbe2276e4abc1718dc1343e2b975b7bd9fb37229b6ff31df874R63-R86) is actually doing two things, checking the user `read_privs` and also the life of the token with the actual request. I reapplied that logic. 

Finally, colors updated to match @maxsibilla updates.
