### ISSUE TITLE
On file uploads POST to ingest-api/file-upload instead of entity-api/file-upload

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#428]
For metadata and image file uploads on the Donors and Samples pages, change the file upload POSTs to use ingest-api/file-upload instead of entity-api/file-upload

**Comment by yuanzhou** [comment]
@shirey The backend functionalities are ready for testing, but will need the corresponding ingest-ui changes for switching /file-upload to ingest-api. The file description update and removal should still call entity-api during entity update since internally the entity-api trigger methods will call ingest-api to commit and remove files.
