### ISSUE TITLE
Label issue - "No translation"

### ISSUE THREAD

**Issue by JAH386** [hubmapconsortium/ingest-ui#905]
The following label problem is present on the Portal. 

The following datesets shows up as “no translation” on the Portal. 

"2 DESI IMS in new - no change (6/27) - *NO TRANSLATION* label [Joel]"

**Comment by pecan88** [comment]
@shirey  - is this something on the Pitt dev side or a different group?

**Comment by pecan88** [comment]
@shirey  - following up here.  Can you share workstream / targets associated with label updates?

**Comment by shirey** [comment]
@bhonick @pecan88 @JAH386 I'm not really clear what the ask is here- but it seems pretty clear that this is an issue in the "Data Portal"- not the Ingest UI.  Harvard manages the data portal in a separate repo but this may be because of some data coming from the the ingest pipeline piece (yet another repo, I think currently managed by David Bentacur Vallejo).  Please close this issue this or move to the appropriate repo.

**Comment by bhonick** [comment]
@shirey Done, added to portal-ui https://github.com/hubmapconsortium/portal-ui/issues/2867
